name: Test Google Sheet Action

on:
    workflow_dispatch:

jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - name: Append row to Google Sheet
              uses: AlbertPuwadol/google-sheet-github-action@main
              with:
                  spreadsheet_id: ${{ secrets.GOOGLE_SHEET_ID }}
                  sheet_name: "Test"
                  values: '["Data 1", "Data 2", 123]'
                  auth_type: "oauth"
                  credentials: ${{ secrets.GOOGLE_OAUTH_TOKEN }}
