name: Test Google Sheet Action

on:
    workflow_dispatch:

jobs:
    test:
        uses: AlbertPuwadol/google-sheet-github-action/.github/workflows/reusable-append-row.yml@main
        with:
            sheet_name: "Feature"
            values: '["${{ github.repository }}", "${{ github.sha }}", "${{ github.actor }}", "${{ github.event.head_commit.message }}"]'
